### ISSUE TITLE
Match suggestions to the picture

### ISSUE THREAD

**Issue by RHurtig** [taylorlapeyre/basicwardrobe.info#10]
First off, love the idea for the site. That being said, how about matching at least one of the suggestions to the example picture you use for the item. For example, the picture in the jacket section doesn't match up with either of the suggested items, it'd be nice if it was at least a close match. Well that's about all I have to suggest, thanks for setting this up.

**Comment by taylorlapeyre** [comment]
Hmm, I can see what you're saying. However, I don't plan on matching pictures to the suggested items since I plan on updating the items over time and didn't want to have to update the picture as well.

The pictures were to give a visual of what a "standard" item of that category would look like, not to show what the suggested items look like.

Thanks for the input though!
